language: go

go:
  - 1.12.x

env:
  - GO111MODULE=on

install: true

jobs:
  include:
    - stage: test
      go: 1.12.x
      script:
        - ./scripts/test.sh
      after_success:
        - bash <(curl -s https://codecov.io/bash)
      cache:
        directories:
          - ${HOME}/.cache/go-build
          - ${HOME}/gopath/pkg/mod
    - stage: build
      go: 1.12.x
      script:
        - ./scripts/build.sh
      deploy:
        provider: releases
        api_key: ""
        file: "modem-scraper_*_*.zip"
        file_glob: true
        skip_cleanup: true
      cache:
        directories:
          - ${HOME}/.cache/go-build
          - ${HOME}/gopath/pkg/mod
